import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./components/providers";
import SigninButton from "./components/signinbutton";
import Link from "next/link";
import SearchBar from "./components/searchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Relate Connect",
  description: "Generated by Hazel, Fathan, and Emily",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Providers>

          <div className=" flex items-center justify-between -mt-6 space-x-1 ">

            <Link href="/">
              <img className="h-40 " src='https://firebasestorage.googleapis.com/v0/b/relate-connect.appspot.com/o/realte_connect_logo-removebg-preview.png?alt=media&token=3b61c20a-63a9-4884-9ec5-50fb4169be46' />
            </Link>

            <SearchBar />
            <SigninButton />
          </div>

          {children}

        </Providers>
      </body>
    </html>
  );
}
