import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './components/providers'
import SigninButton from './components/signinbutton'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Relate Connect',
  description: 'Generated by Hazel, Fathan, and Emily',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

          <ul className='flex justify-center m-4 space-x-8'>

            <li className='text-center'><Link href="/">Home</Link></li> 
            <SigninButton /> 

          </ul>


          {children}
      

        </Providers>


        
      </body>
    </html>
  )
}
